services:
  app:
    image: eclipse-temurin:24-jdk
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      NEO4J_URL: bolt://neo4j-db:7687
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/5@5,?g)$+ZW'
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins

volumes:
  neo4j-data:
